---
address: "2.tcp.eu.ngrok.io:19210"
credentials:
  auth_type: UserPassword
  password_sops: "ENC[AES256_GCM,data:YuwBJvrQcc0OHQAUijWL9Q==,iv:q1lSqxyX3M3ZoXC3tIYd4SJ87V7ROGELgsKJdJuscNM=,tag:id1jrPWbBaujZFpne9Cw9Q==,type:str]"
database: estuary_db
historyMode: false
user: postgres
sops:
  kms: ~
  gcp_kms:
    - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/catalog-sops/cryptoKeys/config-encryptor
      created_at: "2025-08-25T10:50:07Z"
      enc: CiUABM8p+4ZLKZrrJHgdWzV7JJSDqVdiqzUN2GJ0BgYHdNX1uEFZEkkAWV/WNkUKg12mpPnGZcvFiqA5WbYhFKHhJxuISp+kQnY0Vbndev1TIQse7fZpdI6DYJFAmBPLNegJnD7LQWTBLNay0V12cocY
  azure_kv: ~
  hc_vault: ~
  age: ~
  lastmodified: "2025-08-25T10:50:07Z"
  mac: "ENC[AES256_GCM,data:wBeESsTij8jpgjdMLowqdcAacwrvb1WmiKK9GepL+/OtowUf+N/rcot2iPjQhcBCHwNuo6UT0ZWHd5VP45/1jh7mXpJTkO3m8LFSdFqQXZ6VeUWIhrr61VUKsexdJhnSjZLCA+Dd5MGLA6vVmxzFDMvdf3Vfv7C4fttLlJk4ars=,iv:35XpbIdyTGuA+XX4lClPsRKU3Vy+JOz27AjQyyCr1d8=,tag:77vHyX/Qlyp7IMGqvGHV4Q==,type:str]"
  pgp: ~
  encrypted_suffix: _sops
  version: 3.7.3
