name: Estuary Pull Specs
description: Pull Estuary specs by either prefix or name
inputs:
  prefix:
    description: Catalog prefix to pull (e.g., sean-estuary/)
    required: false
  name:
    description: Full catalog name to pull (capture, collection, derivation, or materialization)
    required: false
runs:
  using: composite
  steps:
    - name: Install flowctl
      shell: bash
      run: |
        set -euo pipefail
        sudo curl -fsSL -o /usr/local/bin/flowctl 'https://github.com/estuary/flow/releases/latest/download/flowctl-x86_64-linux'
        sudo chmod +x /usr/local/bin/flowctl
        flowctl -V
    - name: Pull specs
      shell: bash
      env:
        PREFIX: ${{ inputs.prefix }}
        NAME: ${{ inputs.name }}
      run: |
        set -euo pipefail
        if [[ -n "${PREFIX:-}" && -n "${NAME:-}" ]]; then
          echo "Error: provide exactly one of 'prefix' or 'name'" >&2
          exit 2
        fi
        if [[ -z "${PREFIX:-}" && -z "${NAME:-}" ]]; then
          echo "Error: one of 'prefix' or 'name' is required" >&2
          exit 2
        fi

        if [[ -n "${PREFIX:-}" ]]; then
          echo "Pulling specs for prefix ${PREFIX}"
          flowctl catalog pull-specs --prefix "${PREFIX}"
        else
          echo "Pulling specs for name ${NAME}"
          flowctl catalog pull-specs --name "${NAME}"
        fi
